name: Publish to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: central
        server-username: ${{ secrets.MAVEN_USERNAME }}
        server-password: ${{ secrets.MAVEN_PASSWORD }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Write settings.xml for Maven Central
      run: |
        mkdir -p $HOME/.m2
        cat <<EOF > $HOME/.m2/settings.xml
<settings>
  <servers>
    <server>
      <id>central</id>
      <username>${{ secrets.MAVEN_USERNAME }}</username>
      <password>${{ secrets.MAVEN_PASSWORD }}</password>
    </server>
  </servers>
</settings>
EOF

    - name: Publish to Maven Central
      run: mvn clean deploy -DperformRelease=true -X -e
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
